"""
База сайтів для /nick.
Формат елементу: {"name": str, "url": str, "m_string": str}
m_string — якщо ця рядок є у відповіді → профілю НЕ існує.
"""
import aiohttp, asyncio, json, logging, time
from pathlib import Path

log = logging.getLogger(__name__)
_CACHE = Path("data/sites.json")
_WMN   = "https://raw.githubusercontent.com/WebBreacher/WhatsMyName/main/wmn-data.json"
_SH    = "https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json"

# ══════════════════════════════════════════════════════════════════════
#  ВБУДОВАНА БАЗА  —  формат (name, url_template, not_found_string)
# ══════════════════════════════════════════════════════════════════════
BUILTIN: list[tuple] = [
    # ── Соцмережі ────────────────────────────────────────────────────
    ("GitHub",            "https://github.com/{}",                                   "Not Found"),
    ("GitLab",            "https://gitlab.com/{}",                                   "404"),
    ("Bitbucket",         "https://bitbucket.org/{}",                                "404"),
    ("Twitter/X",         "https://x.com/{}",                                        "This account doesn't exist"),
    ("Instagram",         "https://www.instagram.com/{}/",                           "Sorry, this page"),
    ("TikTok",            "https://www.tiktok.com/@{}",                              "Couldn't find this account"),
    ("YouTube",           "https://www.youtube.com/@{}",                             ""),
    ("Reddit",            "https://www.reddit.com/user/{}/",                         "page not found"),
    ("LinkedIn",          "https://www.linkedin.com/in/{}",                          ""),
    ("Pinterest",         "https://www.pinterest.com/{}/",                           ""),
    ("Snapchat",          "https://www.snapchat.com/add/{}",                         ""),
    ("Telegram",          "https://t.me/{}",                                         "If you have Telegram"),
    ("VK",                "https://vk.com/{}",                                       ""),
    ("OK.ru",             "https://ok.ru/{}",                                        ""),
    ("Twitch",            "https://www.twitch.tv/{}",                                ""),
    ("Steam",             "https://steamcommunity.com/id/{}",                        "The specified profile"),
    ("Facebook",          "https://www.facebook.com/{}",                             ""),
    ("Threads",           "https://www.threads.net/@{}",                             ""),
    ("Bluesky",           "https://bsky.app/profile/{}",                             ""),
    ("Mastodon Social",   "https://mastodon.social/@{}",                             ""),
    ("Mastodon Online",   "https://mastodon.online/@{}",                             ""),
    ("Fosstodon",         "https://fosstodon.org/@{}",                               ""),
    ("Infosec.exchange",  "https://infosec.exchange/@{}",                            ""),
    ("Hachyderm",         "https://hachyderm.io/@{}",                                ""),
    ("Gab",               "https://gab.com/{}",                                      ""),
    ("Minds",             "https://www.minds.com/{}",                                ""),
    ("Parler",            "https://parler.com/{}",                                   ""),
    ("TruthSocial",       "https://truthsocial.com/@{}",                             ""),
    ("Rumble",            "https://rumble.com/user/{}",                              ""),
    ("Odysee",            "https://odysee.com/@{}",                                  ""),
    ("BitChute",          "https://www.bitchute.com/channel/{}/",                    ""),
    ("Dailymotion",       "https://www.dailymotion.com/{}",                          ""),
    ("Vimeo",             "https://vimeo.com/{}",                                    ""),
    ("Cohost",            "https://cohost.org/{}",                                   ""),
    ("Pixelfed Social",   "https://pixelfed.social/@{}",                             ""),
    ("Misskey IO",        "https://misskey.io/@{}",                                  ""),
    ("Lemmy World",       "https://lemmy.world/u/{}",                                ""),
    ("Kick.com",          "https://kick.com/{}",                                     ""),
    ("Trovo",             "https://trovo.live/{}",                                   ""),
    ("Nimo.tv",           "https://www.nimo.tv/{}",                                  ""),
    ("Bigo Live",         "https://www.bigo.tv/{}",                                  ""),
    ("Afreeca",           "https://bj.afreecatv.com/{}",                             ""),
    ("DLive",             "https://dlive.tv/{}",                                     ""),
    ("Caffeine.tv",       "https://www.caffeine.tv/{}",                              ""),
    ("WeChat",            "https://weixin.qq.com/r/{}",                              ""),
    ("WhatsApp",          "https://wa.me/{}",                                        ""),
    ("Line",              "https://line.me/R/ti/p/@{}",                              ""),
    ("Kik",               "https://www.kik.com/#{}",                                 ""),
    ("Discord",           "https://discord.com/users/{}",                            ""),
    ("Signal",            "https://signal.me/#p/{}",                                 ""),
    ("Viber",             "https://invite.viber.com/?g2={}",                         ""),
    ("Wickr",             "https://wickr.com/{}",                                    ""),
    ("Clubhouse",         "https://www.clubhouse.com/@{}",                           ""),
    ("BeReal",            "https://bere.al/{}",                                      ""),
    ("Lemon8",            "https://www.lemon8-app.com/@{}",                          ""),
    ("Poparazzi",         "https://poparazzi.com/{}",                                ""),
    # ── Розробка / Код ───────────────────────────────────────────────
    ("Medium",            "https://medium.com/@{}",                                  "404"),
    ("Dev.to",            "https://dev.to/{}",                                       "404"),
    ("HackerNews",        "https://news.ycombinator.com/user?id={}",                 "No such user"),
    ("CodePen",           "https://codepen.io/{}",                                   "404"),
    ("Replit",            "https://replit.com/@{}",                                  "404"),
    ("HackerRank",        "https://www.hackerrank.com/{}",                           "404"),
    ("LeetCode",          "https://leetcode.com/{}",                                 ""),
    ("Codeforces",        "https://codeforces.com/profile/{}",                       ""),
    ("AtCoder",           "https://atcoder.jp/users/{}",                             ""),
    ("Kaggle",            "https://www.kaggle.com/{}",                               ""),
    ("npm",               "https://www.npmjs.com/~{}",                               ""),
    ("PyPI",              "https://pypi.org/user/{}/",                               "404"),
    ("DockerHub",         "https://hub.docker.com/u/{}",                             "404"),
    ("SourceForge",       "https://sourceforge.net/u/{}/profile",                    ""),
    ("Launchpad",         "https://launchpad.net/~{}",                               ""),
    ("HuggingFace",       "https://huggingface.co/{}",                               ""),
    ("Gist GitHub",       "https://gist.github.com/{}",                              ""),
    ("Hashnode",          "https://hashnode.com/@{}",                                ""),
    ("freeCodeCamp",      "https://www.freecodecamp.org/{}",                         ""),
    ("Codecademy",        "https://www.codecademy.com/profiles/{}",                  ""),
    ("Exercism",          "https://exercism.io/profiles/{}",                         ""),
    ("Codeberg",          "https://codeberg.org/{}",                                 ""),
    ("Sourcehut",         "https://sr.ht/~{}",                                       ""),
    ("JSFiddle",          "https://jsfiddle.net/user/{}",                            ""),
    ("CodeSandbox",       "https://codesandbox.io/u/{}",                             ""),
    ("StackBlitz",        "https://stackblitz.com/@{}",                              ""),
    ("Glitch",            "https://glitch.com/@{}",                                  ""),
    ("Observable",        "https://observablehq.com/@{}",                            ""),
    ("HuggingFace Hub",   "https://huggingface.co/spaces/{}",                        ""),
    ("Weights & Biases",  "https://wandb.ai/{}",                                     ""),
    ("NuGet",             "https://www.nuget.org/profiles/{}",                       ""),
    ("RubyGems",          "https://rubygems.org/profiles/{}",                        ""),
    ("Packagist",         "https://packagist.org/users/{}/",                         ""),
    ("Crates.io",         "https://crates.io/users/{}",                              ""),
    ("Hex.pm",            "https://hex.pm/users/{}",                                 ""),
    ("Cocoapods",         "https://cocoapods.org/owners/{}",                         ""),
    ("AUR",               "https://aur.archlinux.org/account/{}",                    ""),
    ("Fedora",            "https://accounts.fedoraproject.org/user/{}/",             ""),
    ("GNOME GitLab",      "https://gitlab.gnome.org/{}",                             ""),
    ("KDE Invent",        "https://invent.kde.org/{}",                               ""),
    ("Drupal",            "https://www.drupal.org/u/{}",                             ""),
    ("WordPress.org",     "https://profiles.wordpress.org/{}/",                      ""),
    ("Stack Overflow",    "https://stackoverflow.com/users/{}",                      ""),
    ("Super User",        "https://superuser.com/users/{}",                          ""),
    ("Server Fault",      "https://serverfault.com/users/{}",                        ""),
    ("Ask Ubuntu",        "https://askubuntu.com/users/{}",                          ""),
    ("Security SE",       "https://security.stackexchange.com/users/{}",             ""),
    ("Crypto SE",         "https://crypto.stackexchange.com/users/{}",               ""),
    ("Unix SE",           "https://unix.stackexchange.com/users/{}",                 ""),
    ("Math SE",           "https://math.stackexchange.com/users/{}",                 ""),
    ("HackerOne",         "https://hackerone.com/{}",                                ""),
    ("Bugcrowd",          "https://bugcrowd.com/{}",                                 ""),
    ("Intigriti",         "https://app.intigriti.com/profile/{}",                    ""),
    ("YesWeHack",         "https://yeswehack.com/hunters/{}",                        ""),
    ("HackerEarth",       "https://www.hackerearth.com/@{}",                         ""),
    ("CTFtime",           "https://ctftime.org/user/{}",                             ""),
    ("TryHackMe",         "https://tryhackme.com/p/{}",                              ""),
    ("HackTheBox",        "https://app.hackthebox.com/profile/{}",                   ""),
    ("PentesterLab",      "https://pentesterlab.com/profile/{}",                     ""),
    ("VulnHub",           "https://www.vulnhub.com/{}",                              ""),
    # ── Фото / Дизайн / Арт ──────────────────────────────────────────
    ("Flickr",            "https://www.flickr.com/people/{}",                        ""),
    ("500px",             "https://500px.com/p/{}",                                  ""),
    ("Unsplash",          "https://unsplash.com/@{}",                                ""),
    ("VSCO",              "https://vsco.co/{}",                                      ""),
    ("Behance",           "https://www.behance.net/{}",                              ""),
    ("Dribbble",          "https://dribbble.com/{}",                                 ""),
    ("DeviantArt",        "https://www.deviantart.com/{}",                           ""),
    ("ArtStation",        "https://www.artstation.com/{}",                           ""),
    ("Newgrounds",        "https://{}.newgrounds.com",                               ""),
    ("Fur Affinity",      "https://www.furaffinity.net/user/{}/",                    ""),
    ("Weasyl",            "https://www.weasyl.com/~{}",                              ""),
    ("Ello",              "https://ello.co/{}",                                      ""),
    ("Cara",              "https://cara.app/{}",                                     ""),
    ("Artfight",          "https://artfight.net/~{}",                                ""),
    ("Toyhouse",          "https://toyhou.se/{}",                                    ""),
    ("Pixiv",             "https://www.pixiv.net/en/users/{}",                       ""),
    ("Sketchfab",         "https://sketchfab.com/{}",                                ""),
    ("NicoNico",          "https://nicovideo.jp/user/{}",                            ""),
    ("Tinami",            "https://www.tinami.com/creator/profile/{}",               ""),
    ("Picarto",           "https://picarto.tv/{}",                                   ""),
    ("CGTrader",          "https://www.cgtrader.com/{}",                             ""),
    ("TurboSquid",        "https://www.turbosquid.com/Search/Artists/{}",            ""),
    ("Clip Studio",       "https://www.clip-studio.com/site/gd_en/csp/userprofile?user={}", ""),
    ("Inkbunny",          "https://inkbunny.net/{}",                                 ""),
    ("e621",              "https://e621.net/users/{}",                               ""),
    # ── Музика ───────────────────────────────────────────────────────
    ("SoundCloud",        "https://soundcloud.com/{}",                               ""),
    ("Spotify",           "https://open.spotify.com/user/{}",                        ""),
    ("Last.fm",           "https://www.last.fm/user/{}",                             "User not found"),
    ("Mixcloud",          "https://www.mixcloud.com/{}/",                            ""),
    ("Bandcamp",          "https://bandcamp.com/{}",                                 ""),
    ("ReverbNation",      "https://www.reverbnation.com/{}",                         ""),
    ("Audiomack",         "https://audiomack.com/{}",                                ""),
    ("Musescore",         "https://musescore.com/{}",                                ""),
    ("Discogs",           "https://www.discogs.com/user/{}",                         ""),
    ("MusicBrainz",       "https://musicbrainz.org/user/{}",                         ""),
    ("Freesound",         "https://freesound.org/people/{}/",                        ""),
    ("Beatport",          "https://www.beatport.com/artist/{}/1",                    ""),
    ("Traxsource",        "https://www.traxsource.com/artist/{}",                    ""),
    ("Jamendo",           "https://www.jamendo.com/artist/{}",                       ""),
    ("Noisetrade",        "https://noisetrade.com/{}",                               ""),
    ("Stereofox",         "https://stereofox.com/artist/{}",                         ""),
    # ── Блоги / Текст ────────────────────────────────────────────────
    ("Tumblr",            "https://{}.tumblr.com",                                   "There's nothing here"),
    ("WordPress",         "https://{}.wordpress.com",                                ""),
    ("Blogger",           "https://{}.blogspot.com",                                 ""),
    ("Substack",          "https://{}.substack.com",                                 ""),
    ("LiveJournal",       "https://{}.livejournal.com",                              ""),
    ("Wattpad",           "https://www.wattpad.com/user/{}",                         ""),
    ("AO3",               "https://archiveofourown.org/users/{}",                    ""),
    ("Fanfiction.net",    "https://www.fanfiction.net/u/{}",                         ""),
    ("Pastebin",          "https://pastebin.com/u/{}",                               ""),
    ("Quora",             "https://www.quora.com/profile/{}",                        ""),
    ("Scribd",            "https://www.scribd.com/{}",                               ""),
    ("SlideShare",        "https://www.slideshare.net/{}",                           ""),
    ("Academia.edu",      "https://independent.academia.edu/{}",                     ""),
    ("ResearchGate",      "https://www.researchgate.net/profile/{}",                 ""),
    ("Goodreads",         "https://www.goodreads.com/{}",                            ""),
    ("Write.as",          "https://write.as/{}",                                     ""),
    ("Micro.blog",        "https://micro.blog/{}",                                   ""),
    ("Ghost",             "https://{}.ghost.io",                                     ""),
    ("Bearblog",          "https://{}.bearblog.dev",                                 ""),
    ("Liveinternet",      "https://www.liveinternet.ru/users/{}/",                   ""),
    ("Diary.ru",          "https://{}.diary.ru",                                     ""),
    ("Яндекс Дзен",       "https://dzen.ru/{}",                                      ""),
    # ── Ігри ─────────────────────────────────────────────────────────
    ("Steam Community",   "https://steamcommunity.com/id/{}",                        "The specified profile"),
    ("itch.io",           "https://{}.itch.io",                                      ""),
    ("Roblox",            "https://www.roblox.com/user.aspx?username={}",            ""),
    ("NameMC",            "https://namemc.com/profile/{}",                           ""),
    ("Chess.com",         "https://www.chess.com/member/{}",                         "Oops"),
    ("Lichess",           "https://lichess.org/@/{}",                                ""),
    ("PSN Profiles",      "https://psnprofiles.com/{}",                              ""),
    ("TwitchTracker",     "https://twitchtracker.com/{}",                            ""),
    ("osu!",              "https://osu.ppy.sh/users/{}",                             ""),
    ("Trakt",             "https://trakt.tv/users/{}",                               ""),
    ("Letterboxd",        "https://letterboxd.com/{}",                               ""),
    ("RAWG",              "https://rawg.io/@{}",                                     ""),
    ("GameBanana",        "https://gamebanana.com/members/{}",                       ""),
    ("Nexusmods",         "https://www.nexusmods.com/users/{}",                      ""),
    ("Modrinth",          "https://modrinth.com/user/{}",                            ""),
    ("SpigotMC",          "https://www.spigotmc.org/members/{}.1/",                  ""),
    ("Speedrun.com",      "https://www.speedrun.com/user/{}",                        ""),
    ("Faceit",            "https://www.faceit.com/en/players/{}",                    ""),
    ("ESEA",              "https://play.esea.net/users/{}",                          ""),
    ("Warcraft Logs",     "https://www.warcraftlogs.com/character/{}",               ""),
    ("Dotabuff",          "https://www.dotabuff.com/players/{}",                     ""),
    ("OP.GG",             "https://op.gg/summoners/kr/{}",                           ""),
    ("MyAnimeList",       "https://myanimelist.net/profile/{}",                      ""),
    ("AniList",           "https://anilist.co/user/{}",                              ""),
    ("Kitsu",             "https://kitsu.io/users/{}",                               ""),
    ("MangaDex",          "https://mangadex.org/user/{}",                            ""),
    ("Anime-Planet",      "https://www.anime-planet.com/users/{}",                   ""),
    ("Kongregate",        "https://www.kongregate.com/accounts/{}", 
